### General Settings ###
baseURL = "https://natgra.github.io/"
languageCode = "en-us"
title = "Natalie's Blog"
publishDir = "docs"

### Theme Settings ### 
theme = "cactus"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[params]
  colortheme = "classic" # dark, light, white, or classic
  mainSection = "posts"